Data = xlsread("Encoder.xlsx");
T = 0.02;
t = 0:T:T*1789 - T;
X = Data(:, 1:3);
V = Data(:, 4:6);
u = Data(:, 7:10);
plot(t, X(:, 1));
hold on;
plot(t, X(:, 2));
grid on;
plot(t, V(:, 1));
hold on;
plot(t, V(:, 2));
grid on;
plot(t, X(:, 3));
grid on;
plot(t, V(:, 3));
grid on;
plot(t, u(:, 1));
hold on;
plot(t, u(:, 2));
hold on;
plot(t, u(:, 3));
hold on;
plot(t, u(:, 4));
grid on;